import { ResumeSuggestionsSchemaType } from "@/schemas/resume-suggestions.schema";

export const resumeSuggestionsMock: ResumeSuggestionsSchemaType = {
  areasToExpand:
    "- **Advanced English Proficiency**: Explicitly state advanced English proficiency in the summary and throughout the resume.  Add a dedicated section for language skills.\n- **Problem-solving skills**: Showcase problem-solving skills and a results-oriented approach in each role's description, quantifying achievements whenever possible.\n- **Teamwork and Collaboration**: Highlight instances of teamwork and collaboration in previous roles, emphasizing positive and empathetic teamwork.\n- **Next.js and React Expertise**: Emphasize specific Next.js and React projects and accomplishments, showcasing depth of knowledge and experience.  Quantify achievements with metrics.\n- **Focus on relevant technologies**:  Prioritize experience with technologies mentioned in the job description (Nest.js, TypeScript, Postgres) if applicable, even if briefly.",
  exampleText:
    '- **Summary**:  Add a sentence highlighting advanced English proficiency and a collaborative work style.  Example: "Highly collaborative and results-oriented Frontend Developer with 8+ years of experience in React, Next.js, and modern web technologies.  Advanced English proficiency enables seamless communication in international teams."\n- **Experience Section**:  In each role, quantify achievements using metrics and highlight problem-solving skills and teamwork. Example: "Collaborated with a team of 5 developers to implement a new feature in Next.js, resulting in a 20% increase in user engagement.  Successfully resolved a critical bug that impacted 10% of users, demonstrating strong problem-solving skills."\n- **Skills Section**: Add a dedicated section for language skills, clearly stating "Advanced English (written and spoken)".  If you have experience with any of the "Nice to Have" technologies, list them prominently.',
  keyJobQualifications:
    "- Advanced English proficiency (written and verbal)\n- 4+ years of professional experience in software development with a strong focus on React and Next.js\n- Excellent written communication and documentation skills\n- Problem-solving mindset\n- Ability to work effectively in a remote, collaborative environment",
};
